### ISSUE TITLE
Extension can't be installed on Visual Studio 2017

### ISSUE THREAD

**Issue by ghost** [pavzaj/visualmutator#4]
I am unable to install the extension in Visual Studio 2017. Are there plans or updates to support newer versions of Visual Studio?:

4/24/2017 9:16:34 PM - 	Identifier         : 3dc60cdc-34a8-47e0-87d5-b85ae22ace17
4/24/2017 9:16:34 PM - 	Name               : VisualMutator
4/24/2017 9:16:34 PM - 	Author             : PiotrTrzpil
4/24/2017 9:16:34 PM - 	Version            : 2.0.8
4/24/2017 9:16:34 PM - 	Description        : VisualMutator info
4/24/2017 9:16:34 PM - 	Locale             : en-US
4/24/2017 9:16:34 PM - 	MoreInfoURL        : 
4/24/2017 9:16:34 PM - 	InstalledByMSI     : False
4/24/2017 9:16:34 PM - 	SupportedFrameworkVersionRange : [4.5]
4/24/2017 9:16:34 PM - 
4/24/2017 9:16:34 PM - 	SignatureState     : Unsigned
4/24/2017 9:16:34 PM - 	Supported Products : 
4/24/2017 9:16:34 PM - 		Microsoft.VisualStudio.Pro
4/24/2017 9:16:34 PM - 			Version : [10.0]
4/24/2017 9:16:34 PM - 		Microsoft.VisualStudio.Pro
4/24/2017 9:16:34 PM - 			Version : [11.0]
4/24/2017 9:16:34 PM - 		Microsoft.VisualStudio.Pro
4/24/2017 9:16:34 PM - 			Version : [12.0]
4/24/2017 9:16:34 PM - 
4/24/2017 9:16:34 PM - 	References         : 
4/24/2017 9:16:34 PM - 		-------------------------------------------------------
4/24/2017 9:16:34 PM - 		Identifier   : Microsoft.VisualStudio.MPF
4/24/2017 9:16:34 PM - 		Name         : Visual Studio MPF
4/24/2017 9:16:34 PM - 		Version      : [11.0,)
4/24/2017 9:16:34 PM - 		MoreInfoURL  : 
4/24/2017 9:16:34 PM - 		Nested       : No
4/24/2017 9:16:34 PM - 
4/24/2017 9:16:34 PM - Signature Details...
4/24/2017 9:16:34 PM - 	Extension is not signed.
4/24/2017 9:16:34 PM - 
4/24/2017 9:16:34 PM - Searching for applicable products...
4/24/2017 9:16:34 PM - Found installed product - Global Location
4/24/2017 9:16:34 PM - Found installed product - Visual Studio Professional 2017
4/24/2017 9:16:34 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by pavzaj** [comment]
I could install it after it was built from this branch:
https://github.com/pavzaj/visualmutator/tree/vs2017

**Comment by connorads** [comment]
Hey @pavzaj I managed to get it installed but it cannot detect my assemblies. Do you know if this supports .NET Core? I'm guessing maybe not!

**Comment by pavzaj** [comment]
Unfortunately it doesn't support. net. core as far as I know.

**Comment by emanuelmarques** [comment]
I have the same problem :/ 
Is there any plans to make it compatible? @pavzaj

**Comment by pavzaj** [comment]
Unfortunately, not in the near future.
