### ISSUE TITLE
VisualMutator.Console Invalid params string options

### ISSUE THREAD

**Issue by fraclipe** [pavzaj/visualmutator#8]
Hi all,

I am not sure if it's a bug or not as far as I have not found any usage example. Sorry if here it is not the right place to put that issue. The problem is that I am not able to run VisualMutator.Console because it always complains with "Invalid params string in options". This is how I am trying to launch it:

>VisualMutator.Console.exe -sourceAssemblies D:\source-code-completed\TestNinja -testAssemblies CustomerControllerTests -resultsXml D:\source-code-completed\myResults.xml

An this is the error reported:
Unhandled Exception: System.Exception: Invalid params string in options.: System.String[]
   at VisualMutator.Console.CommandLineParser.ParseFrom(String[] args) in C:\PLIKI\VisualMutator\VisualMutator\VisualMutator.Console\CommandLineParser.cs:line 18
   at VisualMutator.Console.Program.Main(String[] args) in C:\PLIKI\VisualMutator\VisualMutator\VisualMutator.Console\Program.cs:line 77

Anyone has any clue about how to solve it?
Thanks in advance

**Comment by pavzaj** [comment]
From what I know, console version is not working at all. Gui version works
in some cases...

**Comment by fraclipe** [comment]
Thanks for the information pavzaj! 

As soon as I'll have some time I will try to understand how the Console code should work in order to try to made the needed changes. In case of success I will report them. I really think is a desirable feature, because could enable the tool to be used in an automated CI/CT environment, like Jenkins for example.

Regarding the GUI version, I have tried the "Save Results..." button/option, and it generates the xml file ONLY when "Include detailed test results for each mutant" and "Include code difference listings for each mutant" are not selected. I think it is important to be able to generate that file at least with the last option selected. Any clues on how to solve that?

Thank you pavzaj for your great work! I am currently using the GUI tool in VS 2017 without any other problems.
